version = 0.1

[default]
[default.global.parameters]
stack_name = "valine-orchestrator-staging"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
s3_prefix = "valine-orchestrator-staging"

[staging]
[staging.global.parameters]
stack_name = "valine-orchestrator-staging"

[staging.build.parameters]
cached = true
parallel = true

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
s3_prefix = "valine-orchestrator-staging"

[prod]
[prod.global.parameters]
stack_name = "valine-orchestrator-prod"

[prod.build.parameters]
cached = true
parallel = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-west-2"
s3_prefix = "valine-orchestrator-prod"
